#!/bin/sh

### BEGIN INIT INFO
# Provides:          bathd
# Required-Start:    $remote_fs $time $network
# Required-Stop:     $remote_fs $time $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: initializes clean up daemon for multi-factor authentication method
# Description:       Bath is a system for adding a factor of authentication 
#                    to any port based service via webservice. bathd is the daemon that
#                    cleans up any expired iptables rules
### END INIT INFO

#set -e

. /lib/lsb/init-functions

DAEMON=/var/lib/bath/app/bathd.py
BASE=bathd
PIDFILE=/var/lib/bath/bathd.pid
USER=www-data

test -x $DAEMON || exit 0

start_bath() { 
	start-stop-daemon --pidfile $PIDFILE --make-pidfile --chuid $USER --background --start --oknodo --exec $DAEMON
}

stop_bath() {
#	killproc -p $PIDFILE && exit 0 || exit $?
	start-stop-daemon --pidfile $PIDFILE --stop --oknodo
}

case "$1" in
	start)
		log_daemon_msg "Starting bath" "bathd"
		start_bath
	;;
	stop)
		log_daemon_msg "Stopping bath" "bathd"
		stop_bath
	;;
	restart)
		log_daemon_msg "Restarting bath" "bathd"
		stop_bath
		start_bath
	;;
	status)
		status_of_proc -p $PIDFILE $DAEMON $BASE && exit 0 || exit $?
	;;
	*)
		echo "Usage: $(basename $0) {start|stop|restart|status}"
	;;
esac

echo 
exit 0
